name: Python application test

on: 
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest bot/tests.py 

  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      - name: Deploy to Server 1
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /home/admin/MusicTousLa
            git pull
            if docker ps | grep -q 'musictousla_music_tous_la_1'; then
              docker-compose restart
            else
              docker-compose up -d
            fi
